name: Fetch Market Data

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install exploratium-quant
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Test with pytest
        run: |
          quant-cli -t "BTC-USD,ETH-USD"
          
      - name: Push to data branch
        uses: Automattic/action-commit-to-branch@master
        with:
          branch: 'download'
          commit_message: 'Automatic push after data fetch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
